baseURL = "https://cuwipatucf.github.io/"
languageCode = "en"
disableLanguages = ["fr"]
title = "CUWiP at UCF 2022"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-37717223-8"

[params]
    title = "CUWiP at UCF 2022"
    date = "2022-01-22"
    description = "CUWiP is the Conference for Undergraduate Women in Physics. The goal of APS CUWiP is to help undergraduate women continue in physics by providing them with the opportunity to experience a professional conference, information about graduate school and professions in physics, and access to other women in physics of all ages with whom they can share experiences, advice, and ideas. The national and local organizing committees of APS CUWiP strive to create a welcoming environment for all, including undergraduate women and gender minorities."
    images = ["/images/logos/ucf-wip-color300.png"]
    email = "ucfwips@gmail.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "UCF CUWiP 2022"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "https://sciences.ucf.edu/physics/wips/"
    appleTouchIcon = "/images/logos/ucf-wip-color300.png"
    favicon32 = "/images/logos/ucf-wip-color300.png"
    favicon16 = "/images/logos/ucf-wip-color300.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    #googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    #jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/ucf-wip-color300.png"
    jumbo = "/images/logos/ucf-wip-color300.png"
    footer = "/images/logos/ucf-wip-gray300.png"

[menu]

[languages]


[languages.en]
    weight = 1
    languageName = "gb"

[languages.fr]
    weight = 2
    languageName = "fr"

[languages.fr.params]
    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
